AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instance with user data, Security Group, and IAM Instance Profile'

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
  AMIParameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  # IAM Instance Profile
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy

  # Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access on port 443
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIParameter
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: env
          Value: dev
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum -y update
            sudo yum -y install ruby
            sudo yum -y install wget
            cd /home/ec2-user
            wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
            sudo chmod +x ./install
            sudo ./install auto
            sudo yum install -y python-pip
            sudo pip install awscli
  TestEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIParameter
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: env
          Value: test
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum -y update
            sudo yum -y install ruby
            sudo yum -y install wget
            cd /home/ec2-user
            wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
            sudo chmod +x ./install
            sudo ./install auto
            sudo yum install -y python-pip
            sudo pip install awscli

