version: 0.0
os: linux
files:
  - source: ansible/frontend/src
    destination: /home/frontend/src/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  Install:
    - location: scripts/start_frontend.sh
      timeout: 300
      runas: frontend
  ApplicationStop:
    - location: scripts/stop_frontend.sh
      timeout: 300
      runas: frontend
