---
- hosts: all
  become: yes

  vars:
    project_name: myproject
    project_dir: /home/backend/src
    django_user: backend
    django_group: backend

  tasks:
    - name: Install Django and Gunicorn
      pip:
        name:
          - django
          - gunicorn
        executable: pip3
        become_user: "{{ django_user }}"
    - name: Copy Django project
      copy:
        src: ./myproject/
        dest: "{{ project_dir }}"
        owner: "{{ django_user }}"
        group: "{{ django_group }}"
    - name: Install project requirements
      pip:
        requirements: "{{ project_dir }}/requirements.txt"
        executable: pip3
        become_user: "{{ django_user }}"
    - name: Create Gunicorn systemd service
      template:
        src: gunicorn.systemd.j2
        dest: /etc/systemd/system/gunicorn.service
      notify:
        - reload systemd
  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

# gunicorn.systemd.j2 (Jinja2 template for the systemd service file)
[Unit]
Description=Gunicorn server for {{ project_name }}

[Service]
User={{ django_user }}
Group={{ django_group }}
WorkingDirectory={{ project_dir }}
ExecStart=/usr/bin/gunicorn --bind 0.0.0.0:8000 {{ project_name }}.wsgi:application
Restart=always

[Install]
WantedBy=multi-user.target
